<?php

namespace App\Http\Controllers;

use App\Models\Payment;
use App\Services\QiCardService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class PaymentController extends Controller
{
    protected QiCardService $qiCardService;

    public function __construct(QiCardService $qiCardService)
    {
        $this->qiCardService = $qiCardService;
    }

    /**
     * Initiate a payment
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function initiate(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'amount' => 'required|numeric|min:0.01',
            'currency' => 'sometimes|string|size:3',
            'description' => 'sometimes|string|max:500',
            'return_url' => 'sometimes|url',
            'callback_url' => 'sometimes|url',
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $user = auth('api')->user();

        // Create payment record (UUID will be auto-generated by the model)
        $payment = Payment::create([
            'user_id' => $user->id,
            'transaction_id' => null, // Will be set to payment ID after creation
            'amount' => $request->amount,
            'currency' => $request->currency ?? 'IQD',
            'status' => 'pending'
        ]);


        // Prepare payment data for QiCard - use payment ID (UUID) as request_id
        $paymentData = [
            "requestId"=> $payment->id,
            "amount"=> $request->amount,
            "currency"=> $request->currency ?? 'IQD',
            "locale"=> "en_US",
            "finishPaymentUrl"=> $request->return_url ?? config('app.url') . '/payment/finish',
            "notificationUrl"=> $request->callback_url ?? config('app.url') . '/api/payment/webhook',
            "customerInfo"=> [
                "firstName"=> $user->first_name ?? $user->name ?? 'Customer',
                "email"=> $user->email,
                "claimCode"=> (string) $payment->id
            ],
            "browserInfo"=> [
                "browserAcceptHeader"=> $request->header('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'),
                "browserIp"=> $request->ip(),
                "browserJavaEnabled"=> false,
                "browserLanguage"=> $request->header('Accept-Language', 'en-US'),
                "browserUserAgent"=> $request->header('User-Agent', 'Mozilla/5.0')
            ],
        ];

        $result = $this->qiCardService->initiatePayment($paymentData);

        if ($result['success']) {
            // Update payment with QiCard payment ID
            $payment->update([
                'qicard_payment_id' => $result['payment_id'] ?? null,
                'qicard_response' => $result['data'] ?? null,
                'status' => 'processing',
            ]);

            return response()->json([
                'success' => true,
                'message' => 'Payment initiated successfully',
                'payment' => [
                    'id' => $payment->id,
                    'amount' => $payment->amount,
                    'currency' => $payment->currency,
                    'status' => $payment->status,
                    'payment_url' => $result['payment_url'],
                ],
            ], 201);
        }

        // Update payment status to failed
        $payment->update([
            'status' => 'failed',
            'qicard_response' => $result,
        ]);

        return response()->json([
            'success' => false,
            'message' => $result['error'] ?? 'Failed to initiate payment',
            'payment' => $payment,
        ], 400);
    }

    /**
     * Get payment status
     *
     * @param string $transactionId
     * @return \Illuminate\Http\JsonResponse
     */
    // public function status($transactionId)
    // {
    //     $user = auth('api')->user();
        
    //     $payment = Payment::where('transaction_id', $transactionId)
    //         ->where('user_id', $user->id)
    //         ->firstOrFail();

    //     // If payment has QiCard payment ID, verify with QiCard
    //     if ($payment->qicard_payment_id) {
    //         $verification = $this->qiCardService->verifyPayment($payment->qicard_payment_id);
            
    //         if ($verification['success']) {
    //             $qicardData = $verification['data'];
    //             $payment->update([
    //                 'qicard_response' => $qicardData,
    //             ]);
    //         }
    //     }

    //     return response()->json([
    //         'success' => true,
    //         'payment' => $payment,
    //     ]);
    // }

    // /**
    //  * Get user's payment history
    //  *
    //  * @param Request $request
    //  * @return \Illuminate\Http\JsonResponse
    //  */
    // public function history(Request $request)
    // {
    //     $user = auth('api')->user();
        
    //     $payments = Payment::where('user_id', $user->id)
    //         ->orderBy('created_at', 'desc')
    //         ->paginate($request->get('per_page', 15));

    //     return response()->json([
    //         'success' => true,
    //         'payments' => $payments,
    //     ]);
    // }

    // /**
    //  * Handle QiCard webhook
    //  *
    //  * @param Request $request
    //  * @return \Illuminate\Http\JsonResponse
    //  */
    // public function webhook(Request $request)
    // {
    //     Log::info('QiCard webhook received', ['data' => $request->all()]);

    //     $webhookData = $request->all();
    //     $result = $this->qiCardService->processWebhook($webhookData);

    //     if (!$result['success']) {
    //         return response()->json([
    //             'success' => false,
    //             'message' => $result['error'],
    //         ], 400);
    //     }

    //     $data = $result['data'];
        
    //     // Find payment by QiCard payment ID or transaction ID
    //     $payment = Payment::where('qicard_payment_id', $data['payment_id'] ?? $data['id'] ?? null)
    //         ->orWhere('transaction_id', $data['order_id'] ?? $data['transaction_id'] ?? null)
    //         ->first();

    //     if (!$payment) {
    //         Log::warning('Payment not found for webhook', ['webhook_data' => $data]);
    //         return response()->json([
    //             'success' => false,
    //             'message' => 'Payment not found',
    //         ], 404);
    //     }

    //     // Update payment status based on webhook
    //     $status = $this->mapQiCardStatus($data['status'] ?? 'unknown');
        
    //     $payment->update([
    //         'status' => $status,
    //         'qicard_response' => $data,
    //         'paid_at' => $status === 'completed' ? now() : null,
    //     ]);

    //     Log::info('Payment updated from webhook', [
    //         'payment_id' => $payment->id,
    //         'status' => $status,
    //     ]);

    //     return response()->json([
    //         'success' => true,
    //         'message' => 'Webhook processed successfully',
    //     ]);
    // }

    // /**
    //  * Handle payment callback (redirect from QiCard)
    //  *
    //  * @param Request $request
    //  * @return \Illuminate\Http\JsonResponse|\Illuminate\View\View
    //  */
    // public function callback(Request $request)
    // {
    //     $transactionId = $request->get('transaction_id') ?? $request->get('order_id');
        
    //     if (!$transactionId) {
    //         return response()->json([
    //             'success' => false,
    //             'message' => 'Transaction ID missing',
    //         ], 400);
    //     }

    //     $payment = Payment::where('transaction_id', $transactionId)->first();

    //     if (!$payment) {
    //         return response()->json([
    //             'success' => false,
    //             'message' => 'Payment not found',
    //         ], 404);
    //     }

    //     // Verify payment status with QiCard
    //     if ($payment->qicard_payment_id) {
    //         $verification = $this->qiCardService->verifyPayment($payment->qicard_payment_id);
            
    //         if ($verification['success']) {
    //             $qicardData = $verification['data'];
    //             $status = $this->mapQiCardStatus($qicardData['status'] ?? 'unknown');
                
    //             $payment->update([
    //                 'status' => $status,
    //                 'qicard_response' => $qicardData,
    //                 'paid_at' => $status === 'completed' ? now() : null,
    //             ]);
    //         }
    //     }

    //     // If return URL is provided in metadata, redirect there
    //     if ($payment->metadata && isset($payment->metadata['return_url'])) {
    //         $returnUrl = $payment->metadata['return_url'];
    //         $separator = strpos($returnUrl, '?') !== false ? '&' : '?';
    //         return redirect($returnUrl . $separator . 'transaction_id=' . $transactionId . '&status=' . $payment->status);
    //     }

    //     return response()->json([
    //         'success' => true,
    //         'payment' => $payment,
    //     ]);
    // }

    // /**
    //  * Handle payment return (user redirect)
    //  *
    //  * @param Request $request
    //  * @return \Illuminate\Http\JsonResponse|\Illuminate\View\View
    //  */
    // public function return(Request $request)
    // {
    //     return $this->callback($request);
    // }

    // /**
    //  * Map QiCard status to our payment status
    //  *
    //  * @param string $qicardStatus
    //  * @return string
    //  */
    // protected function mapQiCardStatus(string $qicardStatus): string
    // {
    //     $statusMap = [
    //         'pending' => 'pending',
    //         'processing' => 'processing',
    //         'completed' => 'completed',
    //         'success' => 'completed',
    //         'paid' => 'completed',
    //         'failed' => 'failed',
    //         'error' => 'failed',
    //         'cancelled' => 'cancelled',
    //         'canceled' => 'cancelled',
    //         'refunded' => 'cancelled',
    //     ];

    //     return $statusMap[strtolower($qicardStatus)] ?? 'pending';
    // }
}

